version: '3.4'

services:
  
  bot:
    build: .
    restart: always
    volumes:
      - /mnt/nas-data/waambot-archives:/archives:rw
      - /mnt/nas-data/waambot-yahoo:/yahoo:rw
    extra_hosts:
    - "host.docker.internal:host-gateway"
